name: Build and Package on Release

on:
  push:
    tags:
      - "v*" # Trigger on tags that start with 'v', e.g., 'v1.0', 'v2.1.3'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step 3: Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore SMPPClient.csproj

      # Step 4: Build the project in Release mode
      - name: Build the project
        run: msbuild .\SMPPClient.csproj /p:Configuration=Release

      # Step 5: Create a directory for packaging
      - name: Prepare package directory
        run: |
          mkdir SMPPClient_Portable
          Copy-Item -Path .\bin\Release\* -Destination SMPPClient_Portable -Recurse

      # Step 6: Create a ZIP file
      - name: Create ZIP package
        run: Compress-Archive -Path .\SMPPClient_Portable\* -DestinationPath SMPPClient_Portable.zip

      # Step 7: Upload the ZIP as a build artifact
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SMPPClient_Portable
          path: SMPPClient_Portable.zip

      # Step 8: Create a GitHub release and attach the ZIP file
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: SMPPClient_Portable.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
